# Generated by Django 4.2.5 on 2023-09-20 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_district_did_province_pid_ward_wid'),
    ]

    operations = [
        migrations.AddField(
            model_name='ward',
            name='province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apis.province'),
        ),
    ]
