# Generated by Django 4.2.5 on 2023-09-20 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_ward_province'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ward',
            name='address',
        ),
        migrations.RemoveField(
            model_name='ward',
            name='date_of_birth',
        ),
    ]
