# Generated by Django 4.2.5 on 2023-09-22 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0006_localgovernment_delete_ward'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('time', models.CharField(max_length=255)),
                ('responsible_person', models.CharField(max_length=255)),
                ('documents', models.ManyToManyField(to='apis.document')),
            ],
        ),
    ]
